# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage/emulated/0/Documents/Leaf-chat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage/emulated/0/Documents/Leaf-chat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Documents/Leaf-chat/CMakeFiles /storage/emulated/0/Documents/Leaf-chat/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Documents/Leaf-chat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Leaf

# Build rule for target.
Leaf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Leaf
.PHONY : Leaf

# fast build rule for target.
Leaf/fast:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/build
.PHONY : Leaf/fast

Leaf-chat/Network/include/Client.o: Leaf-chat/Network/include/Client.cpp.o

.PHONY : Leaf-chat/Network/include/Client.o

# target to build an object file
Leaf-chat/Network/include/Client.cpp.o:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/Network/include/Client.cpp.o
.PHONY : Leaf-chat/Network/include/Client.cpp.o

Leaf-chat/Network/include/Client.i: Leaf-chat/Network/include/Client.cpp.i

.PHONY : Leaf-chat/Network/include/Client.i

# target to preprocess a source file
Leaf-chat/Network/include/Client.cpp.i:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/Network/include/Client.cpp.i
.PHONY : Leaf-chat/Network/include/Client.cpp.i

Leaf-chat/Network/include/Client.s: Leaf-chat/Network/include/Client.cpp.s

.PHONY : Leaf-chat/Network/include/Client.s

# target to generate assembly for a file
Leaf-chat/Network/include/Client.cpp.s:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/Network/include/Client.cpp.s
.PHONY : Leaf-chat/Network/include/Client.cpp.s

Leaf-chat/Network/include/Network.o: Leaf-chat/Network/include/Network.cpp.o

.PHONY : Leaf-chat/Network/include/Network.o

# target to build an object file
Leaf-chat/Network/include/Network.cpp.o:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/Network/include/Network.cpp.o
.PHONY : Leaf-chat/Network/include/Network.cpp.o

Leaf-chat/Network/include/Network.i: Leaf-chat/Network/include/Network.cpp.i

.PHONY : Leaf-chat/Network/include/Network.i

# target to preprocess a source file
Leaf-chat/Network/include/Network.cpp.i:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/Network/include/Network.cpp.i
.PHONY : Leaf-chat/Network/include/Network.cpp.i

Leaf-chat/Network/include/Network.s: Leaf-chat/Network/include/Network.cpp.s

.PHONY : Leaf-chat/Network/include/Network.s

# target to generate assembly for a file
Leaf-chat/Network/include/Network.cpp.s:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/Network/include/Network.cpp.s
.PHONY : Leaf-chat/Network/include/Network.cpp.s

Leaf-chat/Network/include/Server.o: Leaf-chat/Network/include/Server.cpp.o

.PHONY : Leaf-chat/Network/include/Server.o

# target to build an object file
Leaf-chat/Network/include/Server.cpp.o:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/Network/include/Server.cpp.o
.PHONY : Leaf-chat/Network/include/Server.cpp.o

Leaf-chat/Network/include/Server.i: Leaf-chat/Network/include/Server.cpp.i

.PHONY : Leaf-chat/Network/include/Server.i

# target to preprocess a source file
Leaf-chat/Network/include/Server.cpp.i:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/Network/include/Server.cpp.i
.PHONY : Leaf-chat/Network/include/Server.cpp.i

Leaf-chat/Network/include/Server.s: Leaf-chat/Network/include/Server.cpp.s

.PHONY : Leaf-chat/Network/include/Server.s

# target to generate assembly for a file
Leaf-chat/Network/include/Server.cpp.s:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/Network/include/Server.cpp.s
.PHONY : Leaf-chat/Network/include/Server.cpp.s

Leaf-chat/src/Application.o: Leaf-chat/src/Application.cpp.o

.PHONY : Leaf-chat/src/Application.o

# target to build an object file
Leaf-chat/src/Application.cpp.o:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/src/Application.cpp.o
.PHONY : Leaf-chat/src/Application.cpp.o

Leaf-chat/src/Application.i: Leaf-chat/src/Application.cpp.i

.PHONY : Leaf-chat/src/Application.i

# target to preprocess a source file
Leaf-chat/src/Application.cpp.i:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/src/Application.cpp.i
.PHONY : Leaf-chat/src/Application.cpp.i

Leaf-chat/src/Application.s: Leaf-chat/src/Application.cpp.s

.PHONY : Leaf-chat/src/Application.s

# target to generate assembly for a file
Leaf-chat/src/Application.cpp.s:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/src/Application.cpp.s
.PHONY : Leaf-chat/src/Application.cpp.s

Leaf-chat/src/Entrypoint.o: Leaf-chat/src/Entrypoint.cpp.o

.PHONY : Leaf-chat/src/Entrypoint.o

# target to build an object file
Leaf-chat/src/Entrypoint.cpp.o:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/src/Entrypoint.cpp.o
.PHONY : Leaf-chat/src/Entrypoint.cpp.o

Leaf-chat/src/Entrypoint.i: Leaf-chat/src/Entrypoint.cpp.i

.PHONY : Leaf-chat/src/Entrypoint.i

# target to preprocess a source file
Leaf-chat/src/Entrypoint.cpp.i:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/src/Entrypoint.cpp.i
.PHONY : Leaf-chat/src/Entrypoint.cpp.i

Leaf-chat/src/Entrypoint.s: Leaf-chat/src/Entrypoint.cpp.s

.PHONY : Leaf-chat/src/Entrypoint.s

# target to generate assembly for a file
Leaf-chat/src/Entrypoint.cpp.s:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/src/Entrypoint.cpp.s
.PHONY : Leaf-chat/src/Entrypoint.cpp.s

Leaf-chat/src/dynamicText.o: Leaf-chat/src/dynamicText.cpp.o

.PHONY : Leaf-chat/src/dynamicText.o

# target to build an object file
Leaf-chat/src/dynamicText.cpp.o:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/src/dynamicText.cpp.o
.PHONY : Leaf-chat/src/dynamicText.cpp.o

Leaf-chat/src/dynamicText.i: Leaf-chat/src/dynamicText.cpp.i

.PHONY : Leaf-chat/src/dynamicText.i

# target to preprocess a source file
Leaf-chat/src/dynamicText.cpp.i:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/src/dynamicText.cpp.i
.PHONY : Leaf-chat/src/dynamicText.cpp.i

Leaf-chat/src/dynamicText.s: Leaf-chat/src/dynamicText.cpp.s

.PHONY : Leaf-chat/src/dynamicText.s

# target to generate assembly for a file
Leaf-chat/src/dynamicText.cpp.s:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/src/dynamicText.cpp.s
.PHONY : Leaf-chat/src/dynamicText.cpp.s

Leaf-chat/src/messenger.o: Leaf-chat/src/messenger.cpp.o

.PHONY : Leaf-chat/src/messenger.o

# target to build an object file
Leaf-chat/src/messenger.cpp.o:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/src/messenger.cpp.o
.PHONY : Leaf-chat/src/messenger.cpp.o

Leaf-chat/src/messenger.i: Leaf-chat/src/messenger.cpp.i

.PHONY : Leaf-chat/src/messenger.i

# target to preprocess a source file
Leaf-chat/src/messenger.cpp.i:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/src/messenger.cpp.i
.PHONY : Leaf-chat/src/messenger.cpp.i

Leaf-chat/src/messenger.s: Leaf-chat/src/messenger.cpp.s

.PHONY : Leaf-chat/src/messenger.s

# target to generate assembly for a file
Leaf-chat/src/messenger.cpp.s:
	$(MAKE) -f CMakeFiles/Leaf.dir/build.make CMakeFiles/Leaf.dir/Leaf-chat/src/messenger.cpp.s
.PHONY : Leaf-chat/src/messenger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Leaf"
	@echo "... Leaf-chat/Network/include/Client.o"
	@echo "... Leaf-chat/Network/include/Client.i"
	@echo "... Leaf-chat/Network/include/Client.s"
	@echo "... Leaf-chat/Network/include/Network.o"
	@echo "... Leaf-chat/Network/include/Network.i"
	@echo "... Leaf-chat/Network/include/Network.s"
	@echo "... Leaf-chat/Network/include/Server.o"
	@echo "... Leaf-chat/Network/include/Server.i"
	@echo "... Leaf-chat/Network/include/Server.s"
	@echo "... Leaf-chat/src/Application.o"
	@echo "... Leaf-chat/src/Application.i"
	@echo "... Leaf-chat/src/Application.s"
	@echo "... Leaf-chat/src/Entrypoint.o"
	@echo "... Leaf-chat/src/Entrypoint.i"
	@echo "... Leaf-chat/src/Entrypoint.s"
	@echo "... Leaf-chat/src/dynamicText.o"
	@echo "... Leaf-chat/src/dynamicText.i"
	@echo "... Leaf-chat/src/dynamicText.s"
	@echo "... Leaf-chat/src/messenger.o"
	@echo "... Leaf-chat/src/messenger.i"
	@echo "... Leaf-chat/src/messenger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

